
ARG VERSION

FROM localhost:5000/jjm2473/jellyfin-rtk-cache:$VERSION

RUN ln -s /usr/lib/jellyfin-ffmpeg/ffprobe /usr/bin/ffprobe\
 && ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg /usr/bin/ffmpeg.img

ADD ./openmax.tar.gz /
ADD ./libffmpeg-full.tar.gz /
ADD ./ffmpeg.tar.gz /
